# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dipendente_complete.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets

from Dipendenti.ControllerDipendenti.ControllerDipendente import ControllerDipendente
from Ui import logo_rc, back_rc


# classe di correlazione tra le funzionalità del controller e le scelte effettuate dall'utente tramite
# l'input/output dell'interfaccia grafica relativa alla visualizzazione di una singola scheda dipendente completa
class Ui_DipendenteComplete(object):
    def __init__(self, dipendente):
        self.controllerDipendente = ControllerDipendente()
        self.controllerDipendente.setModel(dipendente)

    # metodo per la configurazione delle label con i valori dell'oggetto dipendente del quale si
    # effettua la visualizzazine completa
    def setLabels(self):
        self.usernameLabel.setText("Username" + "\n\n" + self.controllerDipendente.model.getUsername())
        self.nominativoLabel.setText("Nominativo" + "\n\n" + self.controllerDipendente.model.getNominativo())
        self.cfLabel.setText("Codice Fiscale" + "\n\n" + self.controllerDipendente.model.getCf())
        self.ruoloLabel.setText("Ruolo" + "\n\n" + self.controllerDipendente.model.getRuolo())

    # metodo per l'eliminazione dal database del dipendente in attuale visualizzazione
    def eliminaDipendente(self):
        try:
            return self.controllerDipendente.deleteLavoratoreByUsername()
        except sqlite3.Error:
            raise

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 651)
        MainWindow.setStyleSheet("background-color: rgb(242,233,216)")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 451, 591))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.minimizeButton = QtWidgets.QPushButton(self.frame)
        self.minimizeButton.setGeometry(QtCore.QRect(400, 10, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.minimizeButton.setFont(font)
        self.minimizeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeButton.setMouseTracking(True)
        self.minimizeButton.setStyleSheet("color:rgb(3, 95, 144);")
        self.minimizeButton.setFlat(True)
        self.minimizeButton.setObjectName("minimizeButton")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)

        self.closeButton = QtWidgets.QPushButton(self.frame)
        self.closeButton.setGeometry(QtCore.QRect(420, 10, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.closeButton.setFont(font)
        self.closeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeButton.setStyleSheet("background-color: rgb(229, 82, 2); \n"
                                       "border-radius:10px;\n"
                                       "color:rgb(3, 95, 144);")
        self.closeButton.setFlat(True)
        self.closeButton.setObjectName("closeButton")

        self.titleLabel = QtWidgets.QLabel(self.frame)
        self.titleLabel.setGeometry(QtCore.QRect(120, 10, 221, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("color:rgb(229, 82, 2);")
        self.titleLabel.setObjectName("titleLabel")

        self.accountMenu = QtWidgets.QComboBox(self.frame)
        self.accountMenu.setGeometry(QtCore.QRect(10, 60, 141, 22))
        self.accountMenu.setStyleSheet("color: rgb(65, 65, 65);")
        self.accountMenu.setCurrentText("")
        self.accountMenu.setFrame(True)
        self.accountMenu.setObjectName("accountMenu")
        self.accountMenu.addItem("")
        self.accountMenu.addItem("")

        self.utenteLabel = QtWidgets.QLabel(self.frame)
        self.utenteLabel.setGeometry(QtCore.QRect(20, 40, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.utenteLabel.setFont(font)
        self.utenteLabel.setStyleSheet("color:rgb(229, 82, 2);")
        self.utenteLabel.setObjectName("utenteLabel")

        self.schedaFrame = QtWidgets.QFrame(self.frame)
        self.schedaFrame.setGeometry(QtCore.QRect(10, 110, 431, 471))
        self.schedaFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.schedaFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.schedaFrame.setObjectName("schedaFrame")

        self.imgLabel = QtWidgets.QLabel(self.schedaFrame)
        self.imgLabel.setGeometry(QtCore.QRect(10, 10, 221, 101))
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")

        self.gridLayoutWidget = QtWidgets.QWidget(self.schedaFrame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 9, 411, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")

        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.usernameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setStyleSheet("color:rgb(229, 82, 2);")
        self.usernameLabel.setObjectName("usernameLabel")
        self.gridLayout.addWidget(self.usernameLabel, 0, 0, 1, 1)

        self.nominativoLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nominativoLabel.setFont(font)
        self.nominativoLabel.setStyleSheet("color:rgb(3, 95, 144);")
        self.nominativoLabel.setObjectName("nominativoLabel")
        self.gridLayout.addWidget(self.nominativoLabel, 0, 1, 1, 1)

        self.cfLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cfLabel.setFont(font)
        self.cfLabel.setStyleSheet("color:rgb(3, 95, 144);")
        self.cfLabel.setObjectName("cfLabel")
        self.gridLayout.addWidget(self.cfLabel, 1, 0, 1, 1)

        self.ruoloLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ruoloLabel.setFont(font)
        self.ruoloLabel.setStyleSheet("color:rgb(3, 95, 144);")
        self.ruoloLabel.setObjectName("ruoloLabel")
        self.gridLayout.addWidget(self.ruoloLabel, 1, 1, 1, 1)

        self.modificaButton = QtWidgets.QPushButton(self.schedaFrame)
        self.modificaButton.setGeometry(QtCore.QRect(10, 430, 201, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.modificaButton.setFont(font)
        self.modificaButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.modificaButton.setStyleSheet("background-color: rgb(3, 95, 144);\n"
                                              "border-radius:10px;\n"
                                              "color:rgb(242,233,216);")
        self.modificaButton.setObjectName("modificaButton")

        self.rimuoviButton = QtWidgets.QPushButton(self.schedaFrame)
        self.rimuoviButton.setGeometry(QtCore.QRect(220, 430, 201, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rimuoviButton.setFont(font)
        self.rimuoviButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rimuoviButton.setStyleSheet("background-color:rgb(229, 82, 2);\n"
                                         "border-radius:10px;\n"
                                         "color:rgb(242,233,216);")
        self.rimuoviButton.setObjectName("rimuoviButton")

        self.logoLabel = QtWidgets.QLabel(self.frame)
        self.logoLabel.setGeometry(QtCore.QRect(380, 40, 61, 61))
        self.logoLabel.setStyleSheet("image:url(:/newPrefix/LoginLogo.png);")
        self.logoLabel.setText("")
        #self.logoLabel.setPixmap(QtGui.QPixmap("../Porojecto/View/logo.png"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setObjectName("logoLabel")

        self.backButton = QtWidgets.QPushButton(self.frame)
        self.backButton.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.backButton.setFont(font)
        self.backButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backButton.setMouseTracking(True)
        self.backButton.setStyleSheet("border-image: url(:/newPrefix/back_button.png);")
        self.backButton.setText("")
        self.backButton.setFlat(True)
        self.backButton.setObjectName("backButton")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.accountMenu.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dipendente"))
        self.minimizeButton.setText(_translate("MainWindow", "-"))
        self.closeButton.setText(_translate("MainWindow", "X"))
        self.titleLabel.setText(_translate("MainWindow", "Visualizza Scheda Dipendente"))
        self.accountMenu.setItemText(0, _translate("MainWindow", "Home"))
        self.accountMenu.setItemText(1, _translate("MainWindow", "Logout"))
        self.utenteLabel.setText(_translate("MainWindow", "NOMEUTENTE"))
        self.usernameLabel.setText(_translate("MainWindow", "Username"))
        self.nominativoLabel.setText(_translate("MainWindow", "Nominativo"))
        self.cfLabel.setText(_translate("MainWindow", "Codice fiscale"))
        self.ruoloLabel.setText(_translate("MainWindow", "Ruolo"))
        self.modificaButton.setText(_translate("MainWindow", "Modifica Dipendente"))
        self.rimuoviButton.setText(_translate("MainWindow", "Rimuovi Dipendente"))
