# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModificaDipendente.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets

from Dipendenti.ControllerDipendenti.ControllerDipendente import ControllerDipendente
from Ui import logo_rc


# classe di correlazione tra le funzionalità del controller e le scelte effettuate dall'utente tramite
# l'input/output dell'interfaccia grafica relativa alla modifica dati del dipendente preso in esame
class UiModificaDipendente(object):
    def __init__(self, dipendente):
        self.controllerDipendente = ControllerDipendente()
        self.controllerDipendente.setModel(dipendente)

    def getModel(self):
        return self.controllerDipendente.getModel()

    # metodo per configurare, al momento dell'apertura dell'interfaccia grafica, le labels di input per la
    # modifica dei dati con i valori attualmente presenti
    def setLabels(self):
        self.newNominativo.setText(self.getModel().getNominativo())
        self.newCf.setText(self.getModel().getCf())
        self.newUsername.setText(self.getModel().getUsername())
        self.newRuolo.setText(self.getModel().getRuolo())

    # metodo per la modifica dei dati del dipendente preso in esame
    def modificaDipendente(self):
        if self.newUsername.text() and self.newCf.text() and self.newRuolo.text() and \
                self.newNominativo.text() and \
                self.controllerDipendente.modificaDipendente(self.newUsername.text(), self.newCf.text(),
                                                             self.newRuolo.text(), self.newNominativo.text()):
            if self.newUsername.text():
                self.controllerDipendente.getModel().setUsername(self.newUsername.text())
            if self.newCf.text():
                self.controllerDipendente.getModel().setCf(self.newCf.text())
            if self.newNominativo.text():
                self.controllerDipendente.getModel().setNominativo(self.newNominativo.text())
            if self.newRuolo.text():
                self.controllerDipendente.getModel().setRuolo(self.newRuolo.text())

            return True

        self.errorLabel.setText("Oops, qualcosa è andato storto!")

    def setupUi(self, ModificaDipendente):
        ModificaDipendente.setObjectName("ModificaDipendente")
        ModificaDipendente.resize(472, 259)
        self.frame = QtWidgets.QFrame(ModificaDipendente)
        self.frame.setGeometry(QtCore.QRect(-20, -10, 501, 271))
        self.frame.setStyleSheet("background-color: rgb(242, 233, 216);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.newNominativo = QtWidgets.QLineEdit(self.frame)
        self.newNominativo.setGeometry(QtCore.QRect(70, 100, 341, 31))
        self.newNominativo.setAutoFillBackground(False)
        self.newNominativo.setStyleSheet("font: 13pt \"Ubuntu\";\n"
                                         "background-color:rgba(0,0,0,0);\n"
                                         "border:2px solid rgba(0,0,0,0);\n"
                                         "color:rgb(3, 95, 144);\n"
                                         "border-bottom-color: rgb(3, 95, 144);\n"
                                         "padding-bottom:10px;")
        self.newNominativo.setText("")
        self.newNominativo.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.newNominativo.setObjectName("newNominativo")

        self.newUsername = QtWidgets.QLineEdit(self.frame)
        self.newUsername.setGeometry(QtCore.QRect(70, 60, 341, 31))
        self.newUsername.setAutoFillBackground(False)
        self.newUsername.setStyleSheet("font: 13pt \"Ubuntu\";\n"
                                       "background-color:rgba(0,0,0,0);\n"
                                       "border:2px solid rgba(0,0,0,0);\n"
                                       "color:rgb(3, 95, 144);\n"
                                       "border-bottom-color: rgb(3, 95, 144);\n"
                                       "padding-bottom:10px;")
        self.newUsername.setText("")
        self.newUsername.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.newUsername.setObjectName("newUsername")

        self.newCf = QtWidgets.QLineEdit(self.frame)
        self.newCf.setGeometry(QtCore.QRect(70, 140, 341, 31))
        self.newCf.setAutoFillBackground(False)
        self.newCf.setStyleSheet("font: 13pt \"Ubuntu\";\n"
                                 "background-color:rgba(0,0,0,0);\n"
                                 "border:2px solid rgba(0,0,0,0);\n"
                                 "color:rgb(3, 95, 144);\n"
                                 "border-bottom-color: rgb(3, 95, 144);\n"
                                 "padding-bottom:10px;")
        self.newCf.setText("")
        self.newCf.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.newCf.setObjectName("newCf")

        self.titleLabel = QtWidgets.QLabel(self.frame)
        self.titleLabel.setGeometry(QtCore.QRect(160, 20, 181, 20))
        self.titleLabel.setStyleSheet("color:rgb(229, 82, 2);\n"
                                 "font: 13pt \"Ubuntu\";")
        self.titleLabel.setObjectName("titleLabel")

        self.closeButton = QtWidgets.QPushButton(self.frame)
        self.closeButton.setGeometry(QtCore.QRect(460, 20, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.closeButton.setFont(font)
        self.closeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeButton.setStyleSheet("background-color: rgb(229, 82, 2); \n"
                                        "border-radius:10px;\n"
                                        "color:rgb(3, 95, 144);")
        self.closeButton.setFlat(True)
        self.closeButton.setObjectName("closeButton")

        self.minimizeButton = QtWidgets.QPushButton(self.frame)
        self.minimizeButton.setGeometry(QtCore.QRect(440, 20, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.minimizeButton.setFont(font)
        self.minimizeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeButton.setMouseTracking(True)
        self.minimizeButton.setStyleSheet("color:rgb(3, 95, 144);")
        self.minimizeButton.setFlat(True)
        self.minimizeButton.setObjectName("minimizeButton")

        self.salvaButton = QtWidgets.QPushButton(self.frame)
        self.salvaButton.setGeometry(QtCore.QRect(340, 220, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.salvaButton.setFont(font)
        self.salvaButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.salvaButton.setStyleSheet("background-color: rgb(3, 95, 144);\n"
                                           "border-radius:10px;\n"
                                           "color:rgb(242,233,216);")
        self.salvaButton.setObjectName("salvaButton")

        self.errorLabel = QtWidgets.QLabel(self.frame)
        self.errorLabel.setGeometry(QtCore.QRect(100, 230, 221, 20))
        self.errorLabel.setStyleSheet("color: rgb(247, 8, 8);")
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")

        self.logoLabel = QtWidgets.QLabel(self.frame)
        self.logoLabel.setGeometry(QtCore.QRect(420, 50, 61, 61))
        self.logoLabel.setStyleSheet("image:url(:/newPrefix/LoginLogo.png)")
        self.logoLabel.setText("")
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setObjectName("logoLabel")

        self.newRuolo = QtWidgets.QLineEdit(self.frame)
        self.newRuolo.setGeometry(QtCore.QRect(70, 180, 341, 31))
        self.newRuolo.setAutoFillBackground(False)
        self.newRuolo.setStyleSheet("font: 13pt \"Ubuntu\";\n"
                                    "background-color:rgba(0,0,0,0);\n"
                                    "border:2px solid rgba(0,0,0,0);\n"
                                    "color:rgb(3, 95, 144);\n"
                                    "border-bottom-color: rgb(3, 95, 144);\n"
                                    "padding-bottom:10px;")
        self.newRuolo.setText("")
        self.newRuolo.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.newRuolo.setObjectName("newRuolo")

        self.retranslateUi(ModificaDipendente)
        QtCore.QMetaObject.connectSlotsByName(ModificaDipendente)
        ModificaDipendente.setTabOrder(self.newUsername, self.newNominativo)
        ModificaDipendente.setTabOrder(self.newNominativo, self.newCf)
        ModificaDipendente.setTabOrder(self.newCf, self.newRuolo)
        ModificaDipendente.setTabOrder(self.newRuolo, self.salvaButton)
        ModificaDipendente.setTabOrder(self.salvaButton, self.minimizeButton)
        ModificaDipendente.setTabOrder(self.minimizeButton, self.closeButton)

    def retranslateUi(self, ModificaDipendente):
        _translate = QtCore.QCoreApplication.translate
        ModificaDipendente.setWindowTitle(_translate("ModificaDipendente", "Modifica Dipendente"))
        self.newNominativo.setPlaceholderText(_translate("ModificaDipendente", "Nominativo"))
        self.newUsername.setPlaceholderText(_translate("ModificaDipendente", "Username"))
        self.newCf.setPlaceholderText(_translate("ModificaDipendente", "Codice Fiscale"))
        self.titleLabel.setWhatsThis(_translate("ModificaDipendente",
                                           "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Modifica Password</span></p></body></html>"))
        self.titleLabel.setText(_translate("ModificaDipendente",
                                      "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Modifica Dipendente</span></p><p align=\"center\"><br/></p></body></html>"))
        self.closeButton.setText(_translate("ModificaDipendente", "X"))
        self.minimizeButton.setText(_translate("ModificaDipendente", "-"))
        self.salvaButton.setText(_translate("ModificaDipendente", "Salva"))
        self.newRuolo.setPlaceholderText(_translate("ModificaDipendente", "Ruolo"))
