# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StrutturaMuseo.json.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Ui import logo_rc

# interfaccia all'utente per la modifica della struttura del museo
class Ui_StrutturaMuseo(object):
    def setupUi(self, StrutturaMuseo):
        StrutturaMuseo.setObjectName("ModificaOpera")
        StrutturaMuseo.resize(371, 240)
        self.frame = QtWidgets.QFrame(StrutturaMuseo)
        self.frame.setGeometry(QtCore.QRect(-20, -10, 391, 251))
        self.frame.setStyleSheet("background-color: rgb(242, 233, 216);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.newCapienzaMax = QtWidgets.QLineEdit(self.frame)
        self.newCapienzaMax.setGeometry(QtCore.QRect(70, 100, 221, 31))
        self.newCapienzaMax.setAutoFillBackground(False)
        self.newCapienzaMax.setStyleSheet("font: 13pt \"Ubuntu\";\n"
"background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"color:rgb(3, 95, 144);\n"
"border-bottom-color: rgb(3, 95, 144);\n"
"padding-bottom:10px;")
        self.newCapienzaMax.setText("")
        self.newCapienzaMax.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.newCapienzaMax.setObjectName("capienzaMax")
        self.newSala = QtWidgets.QLineEdit(self.frame)
        self.newSala.setGeometry(QtCore.QRect(70, 60, 221, 31))
        self.newSala.setAutoFillBackground(False)
        self.newSala.setStyleSheet("font: 13pt \"Ubuntu\";\n"
"background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"color:rgb(3, 95, 144);\n"
"border-bottom-color: rgb(3, 95, 144);\n"
"padding-bottom:10px;")
        self.newSala.setText("")
        self.newSala.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.newSala.setObjectName("newSala")
        self.Title = QtWidgets.QLabel(self.frame)
        self.Title.setGeometry(QtCore.QRect(120, 20, 181, 20))
        self.Title.setStyleSheet("color:rgb(229, 82, 2);\n"
"font: 13pt \"Ubuntu\";\n"
"")
        self.Title.setObjectName("Title")
        self.closeButton = QtWidgets.QPushButton(self.frame)
        self.closeButton.setGeometry(QtCore.QRect(350, 20, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.closeButton.setFont(font)
        self.closeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeButton.setStyleSheet("background-color: rgb(229, 82, 2); \n"
"border-radius:10px;\n"
"color:rgb(3, 95, 144);")
        self.closeButton.setFlat(True)
        self.closeButton.setObjectName("closeButton")
        self.minimizeButton = QtWidgets.QPushButton(self.frame)
        self.minimizeButton.setGeometry(QtCore.QRect(330, 20, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.minimizeButton.setFont(font)
        self.minimizeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeButton.setMouseTracking(True)
        self.minimizeButton.setStyleSheet("color:rgb(3, 95, 144);")
        self.minimizeButton.setFlat(True)
        self.minimizeButton.setObjectName("minimizeButton")
        self.salvaStruttura = QtWidgets.QPushButton(self.frame)
        self.salvaStruttura.setGeometry(QtCore.QRect(250, 150, 111, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 233, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 95, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 233, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 233, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 95, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 95, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 233, 216, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 233, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 95, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 233, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 233, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 95, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 95, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 233, 216, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 233, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 95, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 233, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 233, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 95, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 95, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 233, 216, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.salvaStruttura.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.salvaStruttura.setFont(font)
        self.salvaStruttura.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.salvaStruttura.setStyleSheet("background-color: rgb(3, 95, 144);\n"
"border-radius:10px;\n"
"color:rgb(242,233,216);")
        self.salvaStruttura.setObjectName("salvaStruttura")
        self.errorLabel = QtWidgets.QLabel(self.frame)
        self.errorLabel.setGeometry(QtCore.QRect(100, 200, 221, 20))
        self.errorLabel.setStyleSheet("color: rgb(247, 8, 8);")
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("ErrorLabel")
        self.logo_label = QtWidgets.QLabel(self.frame)
        self.logo_label.setGeometry(QtCore.QRect(310, 50, 61, 61))
        self.logo_label.setStyleSheet("image:url(:/newPrefix/LoginLogo.png)")
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap("../Porojecto/View/logo.png"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")

        self.retranslateUi(StrutturaMuseo)
        QtCore.QMetaObject.connectSlotsByName(StrutturaMuseo)
        StrutturaMuseo.setTabOrder(self.newSala, self.newCapienzaMax)
        StrutturaMuseo.setTabOrder(self.newCapienzaMax, self.salvaStruttura)
        StrutturaMuseo.setTabOrder(self.salvaStruttura, self.minimizeButton)
        StrutturaMuseo.setTabOrder(self.minimizeButton, self.closeButton)

    def retranslateUi(self, ModificaOpera):
        _translate = QtCore.QCoreApplication.translate
        ModificaOpera.setWindowTitle(_translate("ModificaOpera", "Form"))
        self.newCapienzaMax.setPlaceholderText(_translate("ModificaOpera", "Capienza Massima"))
        self.newSala.setPlaceholderText(_translate("ModificaOpera", "Nuova Sala"))
        self.Title.setWhatsThis(_translate("ModificaOpera", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Modifica Password</span></p></body></html>"))
        self.Title.setText(_translate("ModificaOpera", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Struttura Museo</span></p></body></html>"))
        self.closeButton.setText(_translate("ModificaOpera", "X"))
        self.minimizeButton.setText(_translate("ModificaOpera", "-"))
        self.salvaStruttura.setText(_translate("ModificaOpera", "Salva "))