from PyQt5 import QtCore, QtGui, QtWidgets
from Ui import logo_rc


class UiAdminHome(object):
    def setupUi(self, AdminMenu):
        AdminMenu.setObjectName("AdminMenu")
        AdminMenu.resize(480, 640)
        AdminMenu.setStyleSheet("background-color: rgb(242,233,216)")
        self.centralwidget = QtWidgets.QWidget(AdminMenu)
        self.centralwidget.setObjectName("centralwidget")

        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 451, 571))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")

        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(20, 120, 411, 371))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")

        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 211, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        self.adminLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.adminLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.adminLayout.setContentsMargins(0, 0, 0, 0)
        self.adminLayout.setObjectName("adminLayout")

        self.mostreButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.mostreButton.setFont(font)
        self.mostreButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mostreButton.setStyleSheet("background-color: rgb(3, 95, 144);; color:rgb(242,233,216);")
        self.mostreButton.setObjectName("mostreButton")
        self.adminLayout.addWidget(self.mostreButton)

        self.dipendentiButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dipendentiButton.setFont(font)
        self.dipendentiButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dipendentiButton.setStyleSheet("background-color: rgb(3, 95, 144);; color:rgb(242,233,216);")
        self.dipendentiButton.setObjectName("dipendentiButton")
        self.adminLayout.addWidget(self.dipendentiButton)

        self.statButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.statButton.setFont(font)
        self.statButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.statButton.setStyleSheet("background-color: rgb(3, 95, 144);; color:rgb(242,233,216);")
        self.statButton.setObjectName("statButton")
        self.adminLayout.addWidget(self.statButton)

        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(210, 40, 201, 331))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")

        self.generalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.generalLayout.setContentsMargins(0, 0, 0, 0)
        self.generalLayout.setObjectName("generalLayout")

        self.visiteButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.visiteButton.setFont(font)
        self.visiteButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.visiteButton.setStyleSheet("background-color: rgb(3, 95, 144);; color:rgb(242,233,216);")
        self.visiteButton.setObjectName("visiteButton")
        self.generalLayout.addWidget(self.visiteButton)

        self.prenotazioniButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.prenotazioniButton.setFont(font)
        self.prenotazioniButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.prenotazioniButton.setStyleSheet("background-color: rgb(3, 95, 144);; color:rgb(242,233,216);")
        self.prenotazioniButton.setObjectName("prenotazioniButton")
        self.generalLayout.addWidget(self.prenotazioniButton)

        self.catalogoButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.catalogoButton.setFont(font)
        self.catalogoButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.catalogoButton.setStyleSheet("background-color: rgb(3, 95, 144);; color:rgb(242,233,216);")
        self.catalogoButton.setObjectName("catalogoButton")
        self.generalLayout.addWidget(self.catalogoButton)

        self.utenteLabel = QtWidgets.QLabel(self.frame)
        self.utenteLabel.setGeometry(QtCore.QRect(40, 30, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.utenteLabel.setFont(font)
        self.utenteLabel.setStyleSheet("color:rgb(229, 82, 2);")
        self.utenteLabel.setObjectName("utenteLabel")

        self.accountMenu = QtWidgets.QComboBox(self.frame)
        self.accountMenu.setGeometry(QtCore.QRect(20, 50, 141, 22))
        self.accountMenu.setStyleSheet("color: rgb(65, 65, 65);")
        self.accountMenu.setCurrentText("")
        self.accountMenu.setFrame(True)
        self.accountMenu.setObjectName("accountMenu")
        self.accountMenu.addItem("")
        self.accountMenu.addItem("")
        self.accountMenu.addItem("")

        self.logoLabel = QtWidgets.QLabel(self.frame)
        self.logoLabel.setGeometry(QtCore.QRect(380, 40, 61, 61))
        self.logoLabel.setStyleSheet("image:url(:/newPrefix/LoginLogo.png)")
        self.logoLabel.setText("")
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setObjectName("logoLabel")

        self.minimizeButton = QtWidgets.QPushButton(self.frame)
        self.minimizeButton.setGeometry(QtCore.QRect(400, 10, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.minimizeButton.setFont(font)
        self.minimizeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeButton.setMouseTracking(True)
        self.minimizeButton.setStyleSheet("color:rgb(3, 95, 144);")
        self.minimizeButton.setFlat(True)
        self.minimizeButton.setObjectName("minimizeButton")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)

        self.closeButton = QtWidgets.QPushButton(self.frame)
        self.closeButton.setGeometry(QtCore.QRect(420, 10, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.closeButton.setFont(font)
        self.closeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeButton.setStyleSheet("color:rgb(3, 95, 144);\n"
                                       "border-radius:10px;\n"
                                       "background-color: rgb(229, 82, 2);")
        self.closeButton.setFlat(True)
        self.closeButton.setObjectName("closeButton")

        AdminMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AdminMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 25))
        self.menubar.setObjectName("menubar")
        AdminMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AdminMenu)
        self.statusbar.setObjectName("statusbar")
        AdminMenu.setStatusBar(self.statusbar)

        self.retranslateUi(AdminMenu)
        self.accountMenu.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(AdminMenu)

    def retranslateUi(self, AdminMenu):
        _translate = QtCore.QCoreApplication.translate
        AdminMenu.setWindowTitle(_translate("AdminMenu", "Admin"))
        self.mostreButton.setText(_translate("AdminMenu", "Gestione Mostre"))
        self.dipendentiButton.setText(_translate("AdminMenu", "Gestione Dipendenti"))
        self.statButton.setText(_translate("AdminMenu", "Statistiche"))
        self.visiteButton.setText(_translate("AdminMenu", "Gestione Visite"))
        self.prenotazioniButton.setText(_translate("AdminMenu", "Gestione Prenotazioni"))
        self.catalogoButton.setText(_translate("AdminMenu", "Catalogo"))
        self.utenteLabel.setText(_translate("AdminMenu", "NOMEUTENTE"))
        self.accountMenu.setItemText(0, _translate("AdminMenu", "Modifica Password"))
        self.accountMenu.setItemText(1, _translate("AdminMenu", "Struttura Museo"))
        self.accountMenu.setItemText(2, _translate("AdminMenu", "Logout"))
        self.minimizeButton.setText(_translate("AdminMenu", "-"))
        self.closeButton.setText(_translate("AdminMenu", "X"))
