# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front_office.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiFrontOfficeHome(object):
    def setupUi(self, FrontOffice):
        FrontOffice.setObjectName("FrontOffice")
        FrontOffice.resize(480, 640)
        FrontOffice.setStyleSheet("background-color: rgb(242,233,216)")

        self.centralWidget = QtWidgets.QWidget(FrontOffice)
        self.centralWidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 451, 571))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")

        self.utenteLabel = QtWidgets.QLabel(self.frame)
        self.utenteLabel.setGeometry(QtCore.QRect(30, 30, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.utenteLabel.setFont(font)
        self.utenteLabel.setStyleSheet("color:rgb(229, 82, 2);")
        self.utenteLabel.setObjectName("utenteLabel")

        self.accountMenu = QtWidgets.QComboBox(self.frame)
        self.accountMenu.setGeometry(QtCore.QRect(20, 50, 141, 22))
        self.accountMenu.setStyleSheet("color: rgb(65, 65, 65);")
        self.accountMenu.setCurrentText("")
        self.accountMenu.setFrame(True)
        self.accountMenu.setObjectName("accountMenu")
        self.accountMenu.addItem("")
        self.accountMenu.addItem("")

        self.minimizeButton = QtWidgets.QPushButton(self.frame)
        self.minimizeButton.setGeometry(QtCore.QRect(400, 10, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.minimizeButton.setFont(font)
        self.minimizeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeButton.setMouseTracking(True)
        self.minimizeButton.setStyleSheet("color:rgb(3, 95, 144);")
        self.minimizeButton.setFlat(True)
        self.minimizeButton.setObjectName("minimizeButton")

        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.closeButton = QtWidgets.QPushButton(self.frame)
        self.closeButton.setGeometry(QtCore.QRect(420, 10, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.closeButton.setFont(font)
        self.closeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeButton.setStyleSheet("background-color: rgb(229, 82, 2); \n"
                                       "border-radius:10px;\n"
                                       "color:rgb(3, 95, 144);")
        self.closeButton.setFlat(True)
        self.closeButton.setObjectName("closeButton")

        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 130, 381, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.prenotazioniButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.prenotazioniButton.setFont(font)
        self.prenotazioniButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.prenotazioniButton.setStyleSheet("background-color: rgb(3, 95, 144); color:rgb(242,233,216);")
        self.prenotazioniButton.setObjectName("prenotazioniButton")
        self.verticalLayout.addWidget(self.prenotazioniButton)

        self.visiteButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.visiteButton.setFont(font)
        self.visiteButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.visiteButton.setStyleSheet("background-color: rgb(3, 95, 144); color:rgb(242,233,216);")
        self.visiteButton.setObjectName("visiteButton")
        self.verticalLayout.addWidget(self.visiteButton)
        self.logoLabel = QtWidgets.QLabel(self.frame)
        self.logoLabel.setGeometry(QtCore.QRect(380, 40, 61, 61))
        self.logoLabel.setStyleSheet("image:url(:/newPrefix/LoginLogo.png)")
        self.logoLabel.setText("")
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setObjectName("logoLabel")

        FrontOffice.setCentralWidget(self.centralWidget)
        self.menubar = QtWidgets.QMenuBar(FrontOffice)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 25))
        self.menubar.setObjectName("menubar")
        FrontOffice.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FrontOffice)
        self.statusbar.setObjectName("statusbar")
        FrontOffice.setStatusBar(self.statusbar)

        self.retranslateUi(FrontOffice)
        self.accountMenu.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(FrontOffice)

    def retranslateUi(self, FrontOffice):
        _translate = QtCore.QCoreApplication.translate
        FrontOffice.setWindowTitle(_translate("FrontOffice", "Front Office"))
        self.utenteLabel.setText(_translate("FrontOffice", "NOMEUTENTE"))
        self.accountMenu.setItemText(0, _translate("FrontOffice", "Modifica Password"))
        self.accountMenu.setItemText(1, _translate("FrontOffice", "Logout"))
        self.minimizeButton.setText(_translate("FrontOffice", "-"))
        self.closeButton.setText(_translate("FrontOffice", "X"))
        self.prenotazioniButton.setText(_translate("FrontOffice", "Gestione Prenotazioni"))
        self.visiteButton.setText(_translate("FrontOffice", "Gestione Visite"))
