# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'catalogo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets
from Ui import back_rc, logo_rc
from opera.ControllerOpera.GestioneCatalogo import GestioneCatalogo


# classe di correlazione tra le funzionalità del controller e le scelte effettuate dall'utente tramite
# l'input/output dell'interfaccia grafica relativa alla visualizzazione delle finestre di aggiunta opera
# nel database e di filtraggio delle opere presenti nel catalogo
class UiCatalogo(object):
    def __init__(self):
        self.gestioneCatalogo = GestioneCatalogo()

    # metodo che restituisce la lista delle opere che rispettano i criteri di filtraggio forniti dall'utente
    def listaOpere(self):

        if self.filtroDataAcquisizioneMin.text() == "Data Acquisizione Min":
            self.filtroDataAcquisizioneMin.setText("")
        if self.filtroDataAcquisizioneMax.text() == "Data Acquisizione Max":
            self.filtroDataAcquisizioneMax.setText("")

        self.gestioneCatalogo.setListaOpere(self.filtroIdLineEdit.text(), self.filtroTitolo.text(),
                                            self.filtroAutore.text(), self.filtroTipologia.text(),
                                            self.filtroDataAcquisizioneMin.text(),
                                            self.filtroDataAcquisizioneMax.text(),
                                            self.filtroAnnoProdMin.text(), self.filtroAnnoProdMax.text(),
                                            self.filtroValoreMin.text(), self.filtroValoreMax.text())
        return self.gestioneCatalogo.getListaOpere()

    # metodo per l'inserimento di una nuova opera nel database
    def nuovaOpera(self):
        if self.dataAcquisizione.text() == "Data Acquisizione":
            self.dataAcquisizione.setText("")

        try:
            try:
                if self.gestioneCatalogo.aggiungiOpera(self.titoloLineEdit.text(), self.autoreLineEdit.text(),
                                                       self.tipoLineEdit.text(), self.dimensioniLineEdit.text(),
                                                       self.annoProdLineEdit.text(), self.immagine.text(),
                                                       self.dataAcquisizione.text(), self.valoreLineEdit.text()):
                    self.clearLabels()
                    self.errorLabel.setStyleSheet("color: rgb(33, 163, 21);")
                    self.errorLabel.setText("Opera aggiunta con successo!")
            except sqlite3.Error:
                self.errorLabel.setStyleSheet("color: rgb(247, 8, 8);")
                self.errorLabel.setText("Opera già presente!")
        except Exception:
            self.errorLabel.setStyleSheet("color: rgb(247, 8, 8);")
            self.errorLabel.setText("Oops, campi vuoti o errati!")

    # metodo per azzerare i valori presenti nelle label dell'interfaccia grafica
    def clearLabels(self):
        self.titoloLineEdit.clear()
        self.autoreLineEdit.clear()
        self.dataAcquisizione.setText("Data Acquisizione")
        self.valoreLineEdit.clear()
        self.immagine.clear()
        self.tipoLineEdit.clear()
        self.dimensioniLineEdit.clear()
        self.annoProdLineEdit.clear()

    def setupUi(self, UI_Catalogo):
        UI_Catalogo.setObjectName("UI_Catalogo")
        UI_Catalogo.resize(480, 648)
        UI_Catalogo.setStyleSheet("background-color: rgb(242,233,216)")

        self.centralwidget = QtWidgets.QWidget(UI_Catalogo)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 451, 591))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.minimizeButton = QtWidgets.QPushButton(self.frame)
        self.minimizeButton.setGeometry(QtCore.QRect(400, 10, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.minimizeButton.setFont(font)
        self.minimizeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeButton.setMouseTracking(True)
        self.minimizeButton.setStyleSheet("color:rgb(3, 95, 144);")
        self.minimizeButton.setFlat(True)
        self.minimizeButton.setObjectName("minimizeButton")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)

        self.closeButton = QtWidgets.QPushButton(self.frame)
        self.closeButton.setGeometry(QtCore.QRect(420, 10, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.closeButton.setFont(font)
        self.closeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeButton.setStyleSheet("background-color: rgb(229, 82, 2);\n"
                                       "border-radius:10px;\n"
                                       "color:rgb(3, 95, 144);")
        self.closeButton.setFlat(True)
        self.closeButton.setObjectName("closeButton")

        self.titleLabel = QtWidgets.QLabel(self.frame)
        self.titleLabel.setGeometry(QtCore.QRect(160, 10, 141, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("color:rgb(229, 82, 2);")
        self.titleLabel.setObjectName("titleLabel")

        self.backButton = QtWidgets.QPushButton(self.frame)
        self.backButton.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.backButton.setFont(font)
        self.backButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backButton.setMouseTracking(True)
        self.backButton.setStyleSheet("border-image: url(:/newPrefix/back_button.png);")
        self.backButton.setText("")
        self.backButton.setFlat(True)
        self.backButton.setObjectName("backButton")

        self.accountMenu = QtWidgets.QComboBox(self.frame)
        self.accountMenu.setGeometry(QtCore.QRect(10, 60, 141, 22))
        self.accountMenu.setStyleSheet("color: rgb(65, 65, 65);")
        self.accountMenu.setCurrentText("")
        self.accountMenu.setFrame(True)
        self.accountMenu.setObjectName("comboBox")
        self.accountMenu.addItem("")
        self.accountMenu.addItem("")

        self.utenteLabel = QtWidgets.QLabel(self.frame)
        self.utenteLabel.setGeometry(QtCore.QRect(20, 40, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.utenteLabel.setFont(font)
        self.utenteLabel.setStyleSheet("color:rgb(229, 82, 2);")
        self.utenteLabel.setObjectName("utenteLabel")

        self.tabWidget_2 = QtWidgets.QTabWidget(self.frame)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 90, 431, 481))
        self.tabWidget_2.setStyleSheet("color:rgb(3, 95, 144);")
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_2.setObjectName("tabWidget_2")

        self.inserisciWidget = QtWidgets.QWidget()
        self.inserisciWidget.setObjectName("inserisciWidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.inserisciWidget)

        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 361, 381))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.titoloLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titoloLineEdit.setFont(font)
        self.titoloLineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                          "border:2px solid rgba(0,0,0,0);\n"
                                          "color:rgb(3, 95, 144);\n"
                                          "border-bottom-color: rgb(3, 95, 144);\n"
                                          "padding-bottom:10px;")
        self.titoloLineEdit.setText("")
        self.titoloLineEdit.setObjectName("titoloLineEdit")
        self.verticalLayout_2.addWidget(self.titoloLineEdit)

        self.autoreLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.autoreLineEdit.setFont(font)
        self.autoreLineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                          "border:2px solid rgba(0,0,0,0);\n"
                                          "color:rgb(3, 95, 144);\n"
                                          "border-bottom-color: rgb(3, 95, 144);\n"
                                          "padding-bottom:10px;")
        self.autoreLineEdit.setText("")
        self.autoreLineEdit.setObjectName("Autore")
        self.verticalLayout_2.addWidget(self.autoreLineEdit)

        self.tipoLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tipoLineEdit.setFont(font)
        self.tipoLineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                        "border:2px solid rgba(0,0,0,0);\n"
                                        "color:rgb(3, 95, 144);\n"
                                        "border-bottom-color: rgb(3, 95, 144);\n"
                                        "padding-bottom:10px;")
        self.tipoLineEdit.setText("")
        self.tipoLineEdit.setObjectName("tipoLineEdit")
        self.verticalLayout_2.addWidget(self.tipoLineEdit)

        self.dimensioniLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dimensioniLineEdit.setFont(font)
        self.dimensioniLineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                              "border:2px solid rgba(0,0,0,0);\n"
                                              "color:rgb(3, 95, 144);\n"
                                              "border-bottom-color: rgb(3, 95, 144);\n"
                                              "padding-bottom:10px;")
        self.dimensioniLineEdit.setText("")
        self.dimensioniLineEdit.setObjectName("dimensioniLineEdit")
        self.verticalLayout_2.addWidget(self.dimensioniLineEdit)

        self.annoProdLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.annoProdLineEdit.setFont(font)
        self.annoProdLineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                            "border:2px solid rgba(0,0,0,0);\n"
                                            "color:rgb(3, 95, 144);\n"
                                            "border-bottom-color: rgb(3, 95, 144);\n"
                                            "padding-bottom:10px;")
        self.annoProdLineEdit.setText("")
        self.annoProdLineEdit.setObjectName("annoProdLineEdit")
        self.verticalLayout_2.addWidget(self.annoProdLineEdit)

        self.immagine = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.immagine.setFont(font)
        self.immagine.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                    "border:2px solid rgba(0,0,0,0);\n"
                                    "color:rgb(3, 95, 144);\n"
                                    "border-bottom-color: rgb(3, 95, 144);\n"
                                    "padding-bottom:10px;")
        self.immagine.setText("")
        self.immagine.setObjectName("Immagine")
        self.verticalLayout_2.addWidget(self.immagine)

        self.dataAcquisizione = QtWidgets.QToolButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataAcquisizione.sizePolicy().hasHeightForWidth())
        self.dataAcquisizione.setSizePolicy(sizePolicy)
        self.dataAcquisizione.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dataAcquisizione.setStyleSheet("background-color: rgb(3, 95, 144);\n"
                                            "border-radius:10px;\n"
                                            "color:rgb(242,233,216);")
        self.dataAcquisizione.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.dataAcquisizione.setMenu(QtWidgets.QMenu(self.dataAcquisizione))
        self.calendar = QtWidgets.QCalendarWidget(self.frame)
        self.calendar.setStyleSheet("background-color: rgb(242,233,216); color: rgb(3, 95, 144);")
        action = QtWidgets.QWidgetAction(self.dataAcquisizione)
        action.setDefaultWidget(self.calendar)
        self.dataAcquisizione.menu().addAction(action)
        self.calendar.clicked.connect(lambda: self.get_date(self.calendar, self.dataAcquisizione))
        self.dataAcquisizione.setObjectName("dataAcquisizione")
        self.verticalLayout_2.addWidget(self.dataAcquisizione)

        self.valoreLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.valoreLineEdit.setFont(font)
        self.valoreLineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                          "border:2px solid rgba(0,0,0,0);\n"
                                          "color:rgb(3, 95, 144);\n"
                                          "border-bottom-color: rgb(3, 95, 144);\n"
                                          "padding-bottom:10px;")
        self.valoreLineEdit.setText("")
        self.valoreLineEdit.setObjectName("valoreLineEdit")
        self.verticalLayout_2.addWidget(self.valoreLineEdit)

        self.inserisciButton = QtWidgets.QPushButton(self.inserisciWidget)
        self.inserisciButton.setGeometry(QtCore.QRect(300, 410, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.inserisciButton.setFont(font)
        self.inserisciButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.inserisciButton.setStyleSheet("background-color: rgb(3, 95, 144);\n"
                                           "border-radius:10px;\n"
                                           "color:rgb(242,233,216);")
        self.inserisciButton.setObjectName("inserisciButton")

        self.label_8 = QtWidgets.QLabel(self.inserisciWidget)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 141, 21))
        self.label_8.setStyleSheet("color:rgb(229, 82, 2);")
        self.label_8.setObjectName("label_8")

        self.errorLabel = QtWidgets.QLabel(self.inserisciWidget)
        self.errorLabel.setGeometry(QtCore.QRect(10, 410, 281, 20))
        self.errorLabel.setStyleSheet("color: rgb(33, 163, 21);")
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")

        self.tabWidget_2.addTab(self.inserisciWidget, "")
        self.visualizza_elenco_2 = QtWidgets.QWidget()
        self.visualizza_elenco_2.setObjectName("visualizza_elenco_2")

        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.visualizza_elenco_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 361, 161))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.filtroIdLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.filtroIdLineEdit.setFont(font)
        self.filtroIdLineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                            "border:2px solid rgba(0,0,0,0);\n"
                                            "color:rgb(3, 95, 144);\n"
                                            "border-bottom-color: rgb(3, 95, 144);\n"
                                            "padding-bottom:10px;")
        self.filtroIdLineEdit.setText("")
        self.filtroIdLineEdit.setObjectName("filtroIdLineEdit")
        self.verticalLayout_3.addWidget(self.filtroIdLineEdit)

        self.filtroTitolo = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.filtroTitolo.setFont(font)
        self.filtroTitolo.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                        "border:2px solid rgba(0,0,0,0);\n"
                                        "color:rgb(3, 95, 144);\n"
                                        "border-bottom-color: rgb(3, 95, 144);\n"
                                        "padding-bottom:10px;")
        self.filtroTitolo.setText("")
        self.filtroTitolo.setObjectName("filtroTitolo")
        self.verticalLayout_3.addWidget(self.filtroTitolo)

        self.filtroAutore = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.filtroAutore.setFont(font)
        self.filtroAutore.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                        "border:2px solid rgba(0,0,0,0);\n"
                                        "color:rgb(3, 95, 144);\n"
                                        "border-bottom-color: rgb(3, 95, 144);\n"
                                        "padding-bottom:10px;")
        self.filtroAutore.setText("")
        self.filtroAutore.setObjectName("filtroAutore")
        self.verticalLayout_3.addWidget(self.filtroAutore)

        self.filtroTipologia = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.filtroTipologia.setFont(font)
        self.filtroTipologia.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                           "border:2px solid rgba(0,0,0,0);\n"
                                           "color:rgb(3, 95, 144);\n"
                                           "border-bottom-color: rgb(3, 95, 144);\n"
                                           "padding-bottom:10px;")
        self.filtroTipologia.setText("")
        self.filtroTipologia.setObjectName("filtroTipologia")
        self.verticalLayout_3.addWidget(self.filtroTipologia)

        self.filtroAutore.raise_()
        self.filtroIdLineEdit.raise_()
        self.filtroTitolo.raise_()
        self.filtroTipologia.raise_()

        self.gridLayoutWidget = QtWidgets.QWidget(self.visualizza_elenco_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 190, 401, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.filtroDataAcquisizioneMin = QtWidgets.QToolButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filtroDataAcquisizioneMin.sizePolicy().hasHeightForWidth())
        self.filtroDataAcquisizioneMin.setSizePolicy(sizePolicy)
        self.filtroDataAcquisizioneMin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.filtroDataAcquisizioneMin.setStyleSheet("background-color: rgb(3, 95, 144);\n"
                                                     "border-radius:10px;\n"
                                                     "color:rgb(242,233,216);")
        self.filtroDataAcquisizioneMin.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.filtroDataAcquisizioneMin.setMenu(QtWidgets.QMenu(self.filtroDataAcquisizioneMin))
        self.calendar_min = QtWidgets.QCalendarWidget(self.gridLayoutWidget)
        self.calendar_min.setStyleSheet("background-color: rgb(242,233,216); color: rgb(3, 95, 144);")
        action = QtWidgets.QWidgetAction(self.filtroDataAcquisizioneMin)
        action.setDefaultWidget(self.calendar_min)
        self.filtroDataAcquisizioneMin.menu().addAction(action)
        self.calendar_min.clicked.connect(lambda: self.get_date(self.calendar_min, self.filtroDataAcquisizioneMin))
        self.filtroDataAcquisizioneMin.setObjectName("filtroDataAcquisizioneMin")
        self.gridLayout.addWidget(self.filtroDataAcquisizioneMin, 0, 0, 1, 1)

        self.filtroValoreMin = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.filtroValoreMin.setFont(font)
        self.filtroValoreMin.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                           "border:2px solid rgba(0,0,0,0);\n"
                                           "color:rgb(3, 95, 144);\n"
                                           "border-bottom-color: rgb(3, 95, 144);\n"
                                           "padding-bottom:10px;")
        self.filtroValoreMin.setText("")
        self.filtroValoreMin.setObjectName("filtroValoreMin")
        self.gridLayout.addWidget(self.filtroValoreMin, 2, 0, 1, 1)

        self.filtroAnnoProdMin = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.filtroAnnoProdMin.setFont(font)
        self.filtroAnnoProdMin.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                             "border:2px solid rgba(0,0,0,0);\n"
                                             "color:rgb(3, 95, 144);\n"
                                             "border-bottom-color: rgb(3, 95, 144);\n"
                                             "padding-bottom:10px;")
        self.filtroAnnoProdMin.setText("")
        self.filtroAnnoProdMin.setObjectName("filtroAnnoProdMin")
        self.gridLayout.addWidget(self.filtroAnnoProdMin, 1, 0, 1, 1)

        self.filtroDataAcquisizioneMax = QtWidgets.QToolButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filtroDataAcquisizioneMax.sizePolicy().hasHeightForWidth())
        self.filtroDataAcquisizioneMax.setSizePolicy(sizePolicy)
        self.filtroDataAcquisizioneMax.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.filtroDataAcquisizioneMax.setStyleSheet("background-color: rgb(3, 95, 144);\n"
                                                     "border-radius:10px;\n"
                                                     "color:rgb(242,233,216);")
        self.filtroDataAcquisizioneMax.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.filtroDataAcquisizioneMax.setMenu(QtWidgets.QMenu(self.filtroDataAcquisizioneMax))
        self.calendar_max = QtWidgets.QCalendarWidget(self.gridLayoutWidget)
        self.calendar_max.setStyleSheet("background-color: rgb(242,233,216); color: rgb(3, 95, 144);")
        action = QtWidgets.QWidgetAction(self.filtroDataAcquisizioneMax)
        action.setDefaultWidget(self.calendar_max)
        self.filtroDataAcquisizioneMax.menu().addAction(action)
        self.calendar_max.clicked.connect(lambda: self.get_date(self.calendar_min, self.filtroDataAcquisizioneMax))
        self.filtroDataAcquisizioneMax.setObjectName("filtroDataAcquisizioneMax")
        self.gridLayout.addWidget(self.filtroDataAcquisizioneMax, 0, 1, 1, 1)

        self.filtroAnnoProdMax = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.filtroAnnoProdMax.setFont(font)
        self.filtroAnnoProdMax.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                             "border:2px solid rgba(0,0,0,0);\n"
                                             "color:rgb(3, 95, 144);\n"
                                             "border-bottom-color: rgb(3, 95, 144);\n"
                                             "padding-bottom:10px;")
        self.filtroAnnoProdMax.setText("")
        self.filtroAnnoProdMax.setObjectName("filtroAnnoProdMax")
        self.gridLayout.addWidget(self.filtroAnnoProdMax, 1, 1, 1, 1)

        self.filtroValoreMax = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.filtroValoreMax.setFont(font)
        self.filtroValoreMax.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                           "border:2px solid rgba(0,0,0,0);\n"
                                           "color:rgb(3, 95, 144);\n"
                                           "border-bottom-color: rgb(3, 95, 144);\n"
                                           "padding-bottom:10px;")
        self.filtroValoreMax.setText("")
        self.filtroValoreMax.setObjectName("filtroValoreMax")
        self.gridLayout.addWidget(self.filtroValoreMax, 2, 1, 1, 1)

        self.visualizzaButton = QtWidgets.QPushButton(self.visualizza_elenco_2)
        self.visualizzaButton.setGeometry(QtCore.QRect(220, 400, 201, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.visualizzaButton.setFont(font)
        self.visualizzaButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.visualizzaButton.setStyleSheet("background-color: rgb(3, 95, 144);\n"
                                            "border-radius:10px;\n"
                                            "color:rgb(242,233,216);")
        self.visualizzaButton.setObjectName("visualizzaButton")
        self.label_5 = QtWidgets.QLabel(self.visualizza_elenco_2)

        self.label_5.setGeometry(QtCore.QRect(10, 0, 221, 21))
        self.label_5.setStyleSheet("color:rgb(3, 95, 144);")
        self.label_5.setObjectName("label_5")
        self.tabWidget_2.addTab(self.visualizza_elenco_2, "")

        self.logoLabel = QtWidgets.QLabel(self.frame)
        self.logoLabel.setGeometry(QtCore.QRect(380, 40, 61, 61))
        self.logoLabel.setStyleSheet("image:url(:/newPrefix/LoginLogo.png)")
        self.logoLabel.setText("")
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setObjectName("logoLabel")
        UI_Catalogo.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(UI_Catalogo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 25))
        self.menubar.setObjectName("menubar")
        UI_Catalogo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UI_Catalogo)
        self.statusbar.setObjectName("statusbar")
        UI_Catalogo.setStatusBar(self.statusbar)

        self.retranslateUi(UI_Catalogo)
        self.accountMenu.setCurrentIndex(-1)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(UI_Catalogo)

    def retranslateUi(self, UI_Catalogo):
        _translate = QtCore.QCoreApplication.translate
        UI_Catalogo.setWindowTitle(_translate("UI_Catalogo", "Catalogo"))
        self.minimizeButton.setText(_translate("UI_Catalogo", "-"))
        self.closeButton.setText(_translate("UI_Catalogo", "X"))
        self.titleLabel.setText(_translate("UI_Catalogo", "Gestione Catalogo"))
        self.accountMenu.setItemText(0, _translate("UI_Catalogo", "Home"))
        self.accountMenu.setItemText(1, _translate("UI_Catalogo", "Logout"))
        self.utenteLabel.setText(_translate("UI_Catalogo", "NOMEUTENTE"))
        self.titoloLineEdit.setPlaceholderText(_translate("UI_Catalogo", "Titolo"))
        self.autoreLineEdit.setPlaceholderText(_translate("UI_Catalogo", "Autore"))
        self.tipoLineEdit.setPlaceholderText(_translate("UI_Catalogo", "Tipologia"))
        self.dimensioniLineEdit.setPlaceholderText(_translate("UI_Catalogo", "Dimensioni"))
        self.annoProdLineEdit.setPlaceholderText(_translate("UI_Catalogo", "Anno di produzione"))
        self.immagine.setPlaceholderText(_translate("UI_Catalogo", "Immagine"))
        self.dataAcquisizione.setText(_translate("UI_Catalogo", "Data acquisizione"))
        self.valoreLineEdit.setPlaceholderText(_translate("UI_Catalogo", "Valore"))
        self.inserisciButton.setText(_translate("UI_Catalogo", "Inserisci"))
        self.label_8.setText(_translate("UI_Catalogo",
                                        "<html><head/><body><p><span style=\" font-weight:600;\">Inserisci opera #ID</span></p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.inserisciWidget),
                                    _translate("UI_Catalogo", "Inserisci Nuova"))
        self.filtroIdLineEdit.setPlaceholderText(_translate("UI_Catalogo", "ID"))
        self.filtroTitolo.setPlaceholderText(_translate("UI_Catalogo", "Titolo"))
        self.filtroAutore.setPlaceholderText(_translate("UI_Catalogo", "Autore"))
        self.filtroTipologia.setPlaceholderText(_translate("UI_Catalogo", "Tipologia"))
        self.filtroDataAcquisizioneMin.setText(_translate("UI_Catalogo", "Data Acquisizione Min"))
        self.filtroValoreMin.setPlaceholderText(_translate("UI_Catalogo", "Valore Min"))
        self.filtroAnnoProdMin.setPlaceholderText(_translate("UI_Catalogo", "Anno Produzione Min"))
        self.filtroDataAcquisizioneMax.setText(_translate("UI_Catalogo", "Data Acquisizione Max"))
        self.filtroAnnoProdMax.setPlaceholderText(_translate("UI_Catalogo", "Anno Produzione Max"))
        self.filtroValoreMax.setPlaceholderText(_translate("UI_Catalogo", "Valore Max"))
        self.visualizzaButton.setText(_translate("UI_Catalogo", "Visualizza elenco filtrato"))
        self.label_5.setText(_translate("UI_Catalogo",
                                        "<html><head/><body><p><span style=\" font-weight:600; color:#e55202;\">Inserimento filtri per la ricerca</span></p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.visualizza_elenco_2),
                                    _translate("UI_Catalogo", "Visualizza elenco"))

    # metodo per scrivere la data scelta sul calendar widget sopra il bottone passato come parametro
    def get_date(self, calendar, button):
        date = calendar.selectedDate()
        button.setText(date.toString("yyyy-MM-dd"))
